# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Test Rcpp function
#'
#'
#' @param test test parameter
#'
#' @export
crtTest <- function(test) {
    .Call(`_j15221_crtTest`, test)
}

crank <- function(v1, v2) {
    .Call(`_j15221_crank`, v1, v2)
}

crank2 <- function(v12) {
    .Call(`_j15221_crank2`, v12)
}

